print("Getting to know you!")
print()
myName = input("What's your name > ")
myFood = input("What's your favourite food > ")
myMusic = input("What's your favourite music > ")
myLive = input("Where do you live? > ")
print()
print("You are")
print(myName)
print("You are probably hungry for")
print(myFood)
print("And you are definitely getting your groove on to")
print(myMusic)
print("Living in the amazing")
print(myLive)
