print("Getting to know you!")
print()
myName: str = input("What's your name > ")
myFood: str = input("What's your favourite food > ")
myMusic: str = input("What's your favourite music > ")
myLive: str = input("Where do you live? > ")
print()
print("You are")
print(myName)
print("You are probably hungry for")
print(myFood)
print("And you are definitely getting your groove on to")
print(myMusic)
print("Living in the amazing")
print(myLive)
